molveno/molveno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from restaurant.views import InventoryPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('reservations/', include('reservations.urls')),
    path('orders/', include('orders.urls')),
]

admin.site.site_header = settings.ADMIN_SITE_HEADER

molveno/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order_history/',views.OrderHistoryView.as_view(), name = 'order_history'),
    path('main', views.IndexView.as_view(), name = 'index'),
    path('food_orders/', views.FoodOrdersList.as_view(), name = 'food_orders'),
    path('drink_orders/', views.DrinkOrdersList.as_view(), name = 'drink_orders'),
    path('orders/recipe/<int:pk>/', views.OrderRecipe.as_view(), name='recipe'),
]

molveno/orders/models.py
from django.db import models

# Create your models here.

molveno/orders/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.base import TemplateView
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.apps import apps
from django.contrib.admin.sites import AlreadyRegistered
from django.contrib import admin, auth, messages
from restaurant.models import *
from django.forms import ModelForm
from datetime import datetime, timedelta


class IndexView(TemplateView):
    template_name = "orders/index.html"


class OrderHistoryView(generic.ListView):
    template_name = 'orders/order_history.html'
    context_object_name = 'complete_order_list'

    def get_queryset(self):
        return Order.objects.all().filter(completed=True)


class FoodOrdersList(TemplateView):
    template_name = 'orders/foodorders.html'

    def get_current_orders(self):
        current_orders = Order.objects.filter(completed=False)
        return current_orders

    def get_food_orders(self):
        current_orders = self.get_current_orders()
        food_orders = [i for i in current_orders if str(i.menu_item.course_type) != 'Drink']
        food_orders = sorted(food_orders, key=lambda order: order.order_time, reverse=False)
        for i in food_orders:
            displayed_time = i.order_time + timedelta(hours=2)
            i.order_time = format(displayed_time, '%H:%M')
        return food_orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['food_orders'] = self.get_food_orders()
        return context

class DrinkOrdersList(TemplateView):
    template_name = 'orders/drinkorders.html'

    def get_current_orders(self):
        current_orders = Order.objects.filter(completed=False)
        return current_orders

    def get_drink_orders(self):
        current_orders = self.get_current_orders()
        drink_orders = [i for i in current_orders if str(i.menu_item.course_type) == 'Drink']
        drink_orders = sorted(drink_orders, key=lambda order: order.order_time, reverse=False)
        for i in drink_orders:
            displayed_time = i.order_time + timedelta(hours=2)
            i.order_time = format(displayed_time, '%H:%M')
        return drink_orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['drink_orders'] = self.get_drink_orders()
        return context

class OrderRecipe(TemplateView):
    template_name = 'orders/orderrecipe.html'

    def get_ingredients(self):
        recipe_ingredients = Ingredient.objects.filter(menu_item__in=MenuItem.objects.filter(id = self.kwargs['pk']))
        return recipe_ingredients

    def get_recipe(self):
        recipe = Order.objects.filter(menu_item__in=MenuItem.objects.filter(id = self.kwargs['pk']))
        return recipe[0].menu_item.recipe

    def get_menu_item(self):
        orders = Order.objects.filter(menu_item__in=MenuItem.objects.filter(id = self.kwargs['pk']))
        return orders[0].menu_item.name

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipe'] = self.get_recipe()
        context['menuitem'] = self.get_menu_item()
        context['ingredients'] = self.get_ingredients()
        return context

molveno/orders/templates/orders/base.html
{% load static  %}
<!DOCTYPE html>
<html>
<head>
{% block head %}
{% endblock %}
<meta charset="UTF-8">
<title>Orders</title>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'orders/style/style.css' %}">

  <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js" type="text/javascript"></script>

  <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css" />

</head>

<body>
  <div id="header">

    <div class="col-md-10 no-padding" id="header-left">
      {% block header-text-left %}
      {% endblock %}
    </div>
    <div class="col-md-2 no-padding" id="header-right">
      {% block header-text-right %}
      {% endblock %}
    </div>

  </div>


  <div class="main-content">

    <div class="row">
      <div class="col-md-12 no-padding">
        <p id="pageTitle">
          {% block page-title %}
          {% endblock %}
        </p>
        {% block content %}
        {% endblock %}
      </div>
      </div>

  </div>

  </div>
</body>

</html>

molveno/orders/templates/orders/drinkorders.html
{% extends 'orders/base.html' %}

{% block head %}
<meta http-equiv="refresh" content="15"/>
{% endblock %}

{% block header-text-left %}
Molveno
{% endblock %}


{% block page-title %}
Drink Orders
{% endblock %}<br>

{% block content %}

{% if drink_orders %}
  <table id="orderstable">
    <tr>
      <th>Item</th>
      <th>Table Number</th>
      <th>Time of order</th>
      <th>Remarks</th>
      <th>Recipe</th>
    </tr>
    {% for x in drink_orders %}
    <tr>
      <td> {{ x.menu_item.name }}</td>
      <td> {{ x.table_no }}</td>
      <td> {{ x.order_time }}</td>
      <td> {{ x.remarks }}</td>
      <td> <a href="{% url 'orders:recipe' x.menu_item.id %}">View recipe</a> </td>
    </tr>
    {% endfor %}
  </table><br>
{% else %}
  <p>There are no orders available.</p>
{% endif %}

<p>
  <input type="button" value="Back" id="backbutton" OnClick="history.go(-1);return true;">
</p>

{% endblock %}

molveno/orders/templates/orders/foodorders.html
{% extends 'orders/base.html' %}

{% block head %}
<meta http-equiv="refresh" content="15"/>
{% endblock %}

{% block header-text-left %}
Molveno
{% endblock %}

{% block page-title %}
Food Orders
{% endblock %}<br>

{% block content %}
{% if food_orders %}
  <table id="orderstable">
    <tr>
      <th>Menu Item</th>
      <th>Table Number</th>
      <th>Time of order</th>
      <th>Remarks</th>
      <th>Recipe</th>
    </tr>
    {% for x in food_orders %}
    <tr>
      <td> {{ x.menu_item.name }}</td>
      <td> {{ x.table_no }}</td>
      <td> {{ x.order_time }}</td>
      <td> {{ x.remarks }}</td>
      <td> <a href="{% url 'orders:recipe' x.menu_item.id %}">View recipe</a> </td>
    </tr>
    {% endfor %}
  </table><br>
{% else %}
  <p>There are no orders available.</p>
{% endif %}



<p>
  <input type="button" value="Back" id="backbutton" OnClick="history.go(-1);return true;">
</p>


{% endblock %}

molveno/orders/templates/orders/index.html
{% extends 'orders/base.html' %}

{% block header-text-left %}
Molveno
{% endblock %}

{% block page-title %}
Orders
{% endblock %}


{% block content %}

<a href="{% url 'orders:food_orders' %}" id="indexbutton">View ordered food</a><br>
<a href="{% url 'orders:drink_orders' %}" id="indexbutton">View ordered drinks</a><br>
<a href="{% url 'orders:order_history' %}" id="indexbutton">View order history</a>

{% endblock %}

molveno/orders/templates/orders/order_history.html
{% extends 'orders/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block page-title %}
Order History
{% endblock %}<br>

{% block content %}
 {% if complete_order_list %}

  <table id="orderstable">
    <tr>
      <th>Order item</th>
      <th>Table number</th>
      <th>Time order placed</th>
      <th>Time order completed</th>
    </tr>
    {% for item in complete_order_list %}
    <tr>
      <td>{{ item }}</td>
      <td>{{ item.table_no }}</td>
      <td>{{ item.order_time|date:'d-m-Y H:i' }}</td>
      <td>{{ item.completed_time|date:'d-m-Y H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
  <br>
 {% else %}
    <p> No completed Orders in History.</p>
 {% endif %}

<p><INPUT TYPE="button" VALUE="Back" id="backbutton" OnClick="history.go( -1 );return true;"></p>

{% endblock %}

molveno/orders/templates/orders/orderrecipe.html
{% extends 'orders/base.html' %}

{% block header-text-left %}
Molveno
{% endblock %}

{% block page-title %}
Recipe for {{menuitem}}
{% endblock %}

{% block content %}

{{recipe}}<br><br>

<h5>Ingredients</h5>
<table id="orderstable">
  <tr>
    <th>Ingredient</th>
    <th>Amount</th>
    <th>Unit</th>
  </tr>
  {% for x in ingredients %}
  <tr>
    <td> {{ x.ingredient.description }}</td>
    <td> {{ x.amount }}</td>
    <td> {{ x.unit }}</td>
  </tr>
  {% endfor %}
</table><br>

<p>
  <input type="button" value="Back" id="backbutton" OnClick="history.go(-1);return true;">
</p>

{% endblock %}