molveno/molveno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from restaurant.views import InventoryPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('reservations/', include('reservations.urls')),
    path('orders/', include('orders.urls')),
]

admin.site.site_header = settings.ADMIN_SITE_HEADER

molveno/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order_history/',views.OrderHistoryView.as_view(), name = 'order_history'),
    path('main', views.IndexView.as_view(), name = 'index'),
    path('food_orders/', views.FoodOrdersList.as_view(), name = 'food_orders'),
    path('drink_orders/', views.DrinkOrdersList.as_view(), name = 'drink_orders'),
    path('orders/recipe/<int:pk>/', views.OrderRecipe.as_view(), name='recipe'),
]

molveno/reservations/urls.py
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('confirmation/', views.ConfirmationView.as_view(), name="confirmation"),
]

molveno/reservations/models.py
from django.db import models
import time

class Table(models.Model):
    '''contains properties for each table in the restaurant '''

    # unique table number
    table_number = models.PositiveIntegerField(unique=True)

    # capacity (number of guests that can be seated on this table)
    capacity = models.PositiveIntegerField(default=2)

    def __str__(self):
        return "Table " + str(self.table_number) + " - " + str(self.capacity) + " persons"

class Reservation(models.Model):
    ''' contains all reservations '''

    # guest name
    name = models.CharField(max_length=200,default="")

    # number of guests
    num_guests = models.PositiveIntegerField(default=0, verbose_name="Guests")

    # date & start time
    start_date_time = models.DateTimeField(verbose_name="Start")

    # duration in minutes
    end_date_time = models.DateTimeField(verbose_name="End")

    # any special requests
    special_request = models.TextField(blank=True)

    # associated table(s)
    table = models.ForeignKey(Table, on_delete=models.PROTECT)

    def __str__(self):
        timezonelocal = 'Europe/Amsterdam'
        #timezone.localtime(timezone.now())
        return "Reservation for " + str(self.num_guests) + " people on " + self.start_date_time.strftime('%d-%m-%Y')

molveno/reservations/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Reservation
from .models import Table

from datetime import datetime
from time import strptime
import re

# Create your views here.
class IndexView(TemplateView):
    template_name = "reservations/index.html"
    confirmation_page = "reservations/confirmation.html"

    def __init__(self):
        self.reservation_concept = Reservation()
        self.reservation_checker = ReservationChecker()
        self.reservation_table = None


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['variable'] = self.value
        print('context data called')
        return context

    def validate_email(self, email):
         if re.match("(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", email) != None:
             return True
         return False

    def save_reservation(self):
        self.reservation_concept.save()

    def post(self,request,*args,**kwargs):
        #check availability
        context = super().get_context_data(**kwargs)

        if "reservation_check" in request.POST:
            print('this is a check only')
            response_for_customer_options = [ "Our restaurant is closed on this date.",
                                        "Our restaurant has no free tables for this number of guests at the selected time.",
                                        "The selected date and time are available! Please confirm your booking."]

            page_actions = ["request_another_date",
                            "request_another_time",
                            "request_booking_confirmation"]
            self.collect_reservation_data_from_post_request(request)
            self.format_reservation(request)

            datetime_valid = self.future_datetime(self.reservation_concept.start_date_time)

            email_valid = self.validate_email(self.email)
            #print('dt',datetime(self.reservation_concept.start_date_time))

            reservation_table = self.reservation_checker.check_reservation_possible(self.selected_num_people,
                                                                                        self.reservation_concept.start_date_time,
                                                                                        self.reservation_concept.end_date_time)
            if reservation_table:
                response_for_customer = response_for_customer_options[2]
                page_action = page_actions[2]
            else:
                response_for_customer = response_for_customer_options[1]
                page_action = page_actions[1]

            variable_content = {"response":response_for_customer,
                                "page_action":page_action,
                                "selected_date":self.selected_date,
                                "selected_time_hours":self.selected_time_hours,
                                "selected_time_minutes":self.selected_time_minutes,
                                "selected_num_people":self.selected_num_people,
                                "email":self.email,
                                "email_valid":email_valid,
                                "phone":self.phone,
                                "selected_num_people":self.selected_num_people,
                                "first_name":self.first_name,
                                "last_name":self.last_name,
                                "remark":self.remark}

            return render(request, IndexView.template_name, variable_content)

        elif "reservation_confirmation" in request.POST:
            # check again if all is available
            self.collect_reservation_data_from_post_request(request)
            self.format_reservation(request)
            self.save_reservation()
            return render(request, self.confirmation_page)
        else:
            return render(request, self.template_name)

    def collect_reservation_data_from_post_request(self,request):
        self.selected_date = request.POST.get("date","")
        self.selected_time_hours = request.POST.get("time-hour","12")
        self.selected_time_minutes = request.POST.get("time-minutes","00")
        self.selected_num_people = request.POST.get("people", "2")
        self.email = request.POST.get("email","")
        self.phone = request.POST.get("phone","")
        self.first_name = request.POST.get("first_name","")
        self.last_name = request.POST.get("last_name","")
        self.remark = request.POST.get("remark","")

    def future_datetime(self, rdatetime):
        return rdatetime >= datetime.now()

    def format_reservation(self,request):
        reservation_name = self.first_name + " " + self.last_name
        reservation_day = int(self.selected_date[:2])
        reservation_month = strptime(self.selected_date[3:6],'%b').tm_mon
        reservation_year = int(self.selected_date[7:11])
        reservation_hour = int(self.selected_time_hours)
        reservation_minutes = int(self.selected_time_minutes)

        reservation_start_datetime = datetime(reservation_year,reservation_month,reservation_day, reservation_hour, reservation_minutes)
        reservation_end_datetime = datetime(reservation_year,reservation_month,reservation_day, reservation_hour+3, reservation_minutes)

        reservation_guests = int(self.selected_num_people)
        reservation_special_request = self.remark
        reservation_table = self.reservation_checker.check_reservation_possible(reservation_guests,
                                                                                reservation_start_datetime,
                                                                                reservation_end_datetime)
        print('table in concept:',reservation_table)


        self.reservation_concept = Reservation( name=reservation_name,
                                                num_guests=reservation_guests,
                                                start_date_time=reservation_start_datetime,
                                                end_date_time=reservation_end_datetime,
                                                special_request=reservation_special_request,
                                                table=reservation_table)

        self.reservation_table = reservation_table
        print(self.reservation_concept)


class ReservationChecker:
    def __init__(self):
        pass

    def get_reservations_for_day(self, start_datetime, end_datetime):
        # smarter would be to check for the start time instantly
        # filter range : endtime >=
        try:
            # any reservations that overlap should remain, as their table numbers have to be checked.
            # overlap means:
            # their start datetime falls between start_datetime and end_datetime OR
            # their end datetime falls between start_time and end_time
            # for OR use Q - objects
            reservations1 = Reservation.objects.filter(start_date_time__range=(start_datetime,end_datetime))
        except Reservation.DoesNotExist:
            reservations1 = None

        try:
            reservations2 = Reservation.objects.filter(end_date_time__range=(start_datetime,end_datetime))
        except Reservation.DoesNotExist:
            reservations2 = None

        print('reservations that start in this range:',reservations1)
        print('reservations that end in this range:',reservations2)

        reservations = reservations1 | reservations2

        return reservations

    def filter_time_span(self, reservations, start_time, end_time):
        reservations.filter(start_date_time)
        filtered_reservations = None
        return filtered_reservations

    def check_reservation_possible(self, num_guests, start_date_time, end_date_time):
        # retrieve all reservations for date, so that these tables can be excluded
        #print('checking',start_date_time,end_date_time)
        reservations = self.get_reservations_for_day(start_date_time, end_date_time)
        print('reservations for ',start_date_time,":",reservations)

        try:
            available_tables = set(Table.objects.all())
        except Table.DoesNotExist:
            available_tables = None

        print('all tables:')
        for t in available_tables:
            print(t)

        if reservations and available_tables:
            for r in reservations:
                if r.table:
                    if t in available_tables:
                        available_tables.remove(t)
        else:
            # no reservations yet
            pass

        print('still available:')
        for t in available_tables:
            print(t)

        #with available tables, calculate what's possible
        resulting_table = self.find_exact_table_match(num_guests, available_tables)
        if not resulting_table:
            resulting_table = self.find_larger_table_match(num_guests, available_tables)

        print('result:',resulting_table)

        return resulting_table

    def find_exact_table_match(self, persons, tables):
        # tables = list
        print('guests:',persons,"; received table options:",tables)
        for t in tables:
            if int(t.capacity) == int(persons):
                return t

    def find_larger_table_match(self, persons, tables):
        #print('finding a larger match')
        #print('received these options for iteration: ',tables)
        table_list = [t for t in tables]
        table_list.sort(key=self.sort_by_capacity)
        #print('sorted tables by capacity:',table_list)
        for t in tables:
            #print('iterating... cap:',t.capacity)
            if int(t.capacity) > int(persons):
                return t

    def sort_by_capacity(self,x):

molveno/reservations/templates/reservations/confirmation.html
{% extends 'reservations/base.html' %}
{% block page-title %}
Reservation Confirmation
{% endblock %}

{% block content %}
<p>
  Thanks for your booking! It has been saved.
</p>
<p>
If you would like to make any changes to your booking, please contact our restaurant:
</p>
<a href="molveno.lake.resort@gmail.com">molveno.lake.resort@gmail.com</a>
<br />
<p>
  <a href="{% url 'reservations:index' %}"><button class="btn btn-primary">Back</button></a>
</p>

{% endblock %}

molveno/reservations/templates/reservations/index.html
{% extends 'reservations/base.html' %}
{% block page-title %}
Molveno Reservations
{% load static %}
{% endblock %}

{% block content %}
Please note that our opening times are from 12:00 - 0:00 daily. <br /> The latest possible booking slot starts at 21:00. <br />
<br />
<p>Make your reservation:</p>

<form name="people" id="reservation_form" method="POST" action="{% url 'reservations:index' %}">
  {% csrf_token %}
  <fieldset id="field">

  <div class="form-row" id="personal-details-1">

    <div class="col-md-2 mb-3">
      <input name="first_name" id="first_name" type="text" class="form-control" placeholder="First name" required>
    </div>

    <div class="col-md-2 mb-3">
      <input name="last_name" id="last_name"  type="text" class="form-control" placeholder="Last name" required>
    </div>

  </div>

  <div class="form-row" id="personal-details-2">

    <div class="col-md-2 mb-3">
      <input name="email" id="email" type="text" class="form-control contactgroup" placeholder="E-mail" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$">
    </div>

    <div name="phone" class="col-md-2 mb-3">
      <input name="phone" id="phone" type="tel" class="form-control contactgroup" placeholder="Phone number">
    </div>

  </div>


  <div class="form-row" id="reservation-form">
    <div class="col-md-2 mb-3">
      <select name="people" class="form-control form-control-mb-2" id="num-people">
        <option value="1">1 person</option>
        <option value="2" selected>2 people</option>
        <option value="3">3 people</option>
        <option value="4">4 people</option>
        <option value="5">5 people</option>
        <option value="6">6 people</option>
        <option value="7">7 people</option>
        <option value="8">8 people</option>
        <option value="9">9 people</option>
        <option value="10">10 people</option>
      </select>
    </div>
  </div>

  <div class="form-row">
    <div class="col-md-2 mb-3">
      <input name="date" id="datepicker" class="form-control-mb-1" width="160" required />
    </div>

  </div>


  <div class="form-row">
    <div class="col-md-1 mb-3">
      <input type="text" pattern="([01]?[0-9]|2[0-3]):[0-5][0-9]"
        required="required" placeholder="hh:mm" id="timefield" class="form-control"/>
    </div>

    <div class="col-auto mb-6">

    </div>
  </div>
  <!--
  <select name="time-hour" type="hidden" id="time-hour-picker">
  </select>
  <select name="time-minutes" type="hidden" id="time-minutes-picker">
  </select>
-->

  <div class="form-row">
    <div class="col-md-4 mb-3">
      <input name="remark" id="remark" type="text" class="form-control" placeholder="Remark (optional)" />
    </div>
  </div>

  <div class="form-row">
    <div class="col-auto mb-3">
      <input type="submit" name="reservation_check" class="btn btn-primary" value="Check availability"/>
    </div>
  </div>
  </fieldset>


  {{ response }}
  {% if page_action %}
  {% endif %}
  <br />
  <br />
  <div class="form-row" id="booking_confirmation" style="display:none">
    <div class="col-auto mb-3">
      <input type="submit" name="reservation_confirmation" value="Confirm booking" class="btn btn-success" action="{% url 'reservations:index' %}" />
    </div>
  </div>

</form>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>

function updateTimeForm(){
  if(datepicker != undefined) {
    var rm = new ReservationTimeViewManager(new Date(), 12, 21);
    var d = new Date(datepicker.val());
    var sel_hrs = parseInt($("#time-hour-picker").val());
    var sel_mnts = parseInt($("#time-minutes-picker").val());
    var currDate = new Date();
    var higherHours = false;
    var closingHour = false;

    if(d.getDate() == currDate.getDate() &&
    d.getMonth() == currDate.getMonth() &&
    d.getFullYear() == currDate.getFullYear()) {
      //console.log('same day selected');
      if(currDate.getHours() < 12){
        console.log('today. still morning');
        d.setMinutes(0);
        d.setHours(0);
      } else if (currDate.getHours() < sel_hrs && sel_hrs != 21){
        console.log('today. higher hours selected than now.');

        d.setMinutes(currDate.getMinutes());
        d.setHours(currDate.getHours());
        higherHours = true;
      } else if (sel_hrs == 21) {
        d.setMinutes(currDate.getMinutes());
        d.setHours(currDate.getHours());
        closingHour = true;
      } else {
        console.log('today. current or lower hours selected than now:');
        d.setMinutes(currDate.getMinutes());
        d.setHours(currDate.getHours());
      }

    } else{
      //console.log('other day selected');
      d.setHours(0);
      d.setMinutes(0);
      if (sel_hrs == 21) {
        closingHour = true;
      }
    }

    rm.updateTime(d);
    h = rm.getNextHoursAsHTML();

    d = rm.getDisplayDate();
    if(closingHour){
      m = rm.getFirstMinutesAsHTML();
      $("#time-minutes-picker").val("00");
      console.log('closing time')
    } else if (higherHours) {
       m = rm.getAllMinutesAsHTML();
    } else {
        m = rm.getNextMinutesAsHTML();
    }
    $("#time-hour-picker" ).html(h);
    $("#time-minutes-picker").html(m);

    //console.log("selected date: ")
  }
  console.log('update')
}

/*$( "#time-hour-picker" ).change(function(e){
  var hourSelected = this.value;
  var minuteSelected = $("#time-minutes-picker").val();
  console.log(minuteSelected);
  updateTimeForm();
  $("#time-hour-picker" ).val(hourSelected);
  //$("#time-minutes-picker").val(minuteSelected);
});*/


Date.prototype.ddmmmyyyy = function() {
  const monthNames = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

var dd = this.getDate();
var mm = monthNames[this.getMonth()].substr(0,3);

return [(dd>9 ? '' : '0') + dd, mm,this.getFullYear()].join(' ');
};

var today, maxDate, datepicker;
today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
oneMonthLater = new Date(new Date().getFullYear(), new Date().getMonth()+1, new Date().getDate());
datepicker = $('#datepicker').datepicker({
  uiLibrary: 'bootstrap4',
  minDate: today,
  maxDate: oneMonthLater,
  format: 'dd mmm yyyy',
  value: today.ddmmmyyyy(),
  /*select: function (e) {
    updateTimeForm();
  },*/
  //change: function(e) {
    //updateTimeForm();
  //}
});

//updateTimeForm();

$( "#reservation_form" ).validate({
  groups: {
    contactgroup: "email phone"
},
  rules: {
    email: {
      require_from_group: [1, ".contactgroup"]
    },
    phone: {
      require_from_group: [1, ".contactgroup"]
    }
  },
  messages: {
    email: {
        require_from_group: "Please provide your phone or e-mail."
    },
    phone: {
        require_from_group: "Please provide your phone or e-mail."
    },
  }
});
var first_name = "{{first_name}}";
var last_name = "{{last_name}}";
var email = "{{email}}";
var phone = "{{phone}}";
var email_valid = "{{email_valid}}"

var selected_num_people = "{{selected_num_people}}";
var selected_date = "{{selected_date}}";
var selected_time_hours = "{{selected_time_hours}}";
var selected_time_minutes = "{{selected_time_minutes}}";
var remark = "{{remark}}";
//updateTimeForm();
if(first_name) document.getElementById('first_name').value = first_name;
if(last_name) document.getElementById('last_name').value = last_name;
if(email) document.getElementById('email').value = email;
if(phone) document.getElementById('phone').value = phone;


if(selected_num_people) document.getElementById('num-people').value = selected_num_people;
if(selected_date) document.getElementById('datepicker').value = selected_date;

if(selected_time_hours && selected_time_minutes ) $("#timefield" ).val(selected_time_hours + ":" + selected_time_minutes);

if(remark) document.getElementById('remark').value = remark;
console.log("email valid?"+email_valid)
if(email_valid == "True"){
  //document.getElementById('email').value = email in django template language;
} else {
  //show error in bootstrap
}

console.log()

var next_action = "{{page_action}}"
console.log("next action "+next_action)

if(next_action == "request_booking_confirmation") {
  document.getElementById('booking_confirmation').style.display = "block";
//  $("#field").attr("disabled","disabled");
  console.log("attempting to disable");
} else if (next_action == "request_another_time") {
  //when it's another action
  document.getElementById('reservation_form').style.display = "block";

}

</script>


<br />
{% endblock %}

molveno/reservations/templates/reservations/opening-times.html
{% extends 'reservations/base.html' %}
{% block page-title %}
  Edit opening times
{% endblock %}
{% block content %}
Opening times

{% endblock %}