molveno/molveno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from restaurant.views import InventoryPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('reservations/', include('reservations.urls')),
    path('orders/', include('orders.urls')),
]

admin.site.site_header = settings.ADMIN_SITE_HEADER

molveno/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('order_history/',views.OrderHistoryView.as_view(), name = 'order_history'),
    path('main', views.IndexView.as_view(), name = 'index'),
    path('food_orders/', views.FoodOrdersList.as_view(), name = 'food_orders'),
    path('drink_orders/', views.DrinkOrdersList.as_view(), name = 'drink_orders'),
    path('orders/recipe/<int:pk>/', views.OrderRecipe.as_view(), name='recipe'),
]

molveno/restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'
urlpatterns = [
    path('entry/<int:table_id>/', views.DrinksList.as_view(), name="entry"),
    path('inventory/', views.InventoryPageView.as_view(), name="inventory"),
    path('restaurant/menu/', views.MenuChangeView.as_view(), name="menu-change-view"),
    path('restaurant/menu/add/', views.MenuAddView.as_view(), name="menu-add-view"),
    path('restaurant/supplier/', views.SupplierChangeView.as_view(), name="supplier-change-view"),
    path('restaurant/supplier/add/', views.SupplierAddView.as_view(), name="supplier-add-view"),
    path('menuitem/<int:pk>/', views.MenuItemView.as_view(), name="menu_item"),
    path('addorder/<int:item_id>/', views.AddOrderItem.as_view(), name="addorder"),
    path('addordermenu/<int:menu_id>/', views.AddOrderMenu.as_view(), name="add-order-menu"),
    path('orders/', views.OrdersView.as_view(), name="orders"),
    path('menucard/<int:table_id>/', views.MenuCardList.as_view(), name="menucard"),
    path('waiter/', views.request_waiter, name="waiter"),
    path('menu/<int:pk>/', views.MenuView.as_view(), name="menu")
]

molveno/orders/models.py
from django.db import models

# Create your models here.

molveno/restaurant/models.py
import datetime
from django.db import models
from decimal import Decimal
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.utils import timezone


class Inventory(models.Model):
    description = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    supplier = models.ForeignKey("Supplier", on_delete=models.PROTECT)
    article_number = models.IntegerField(default=0)

    UNIT_CHOICES = (
        ('KG', 'Kilogram'),
        ('PCS', 'Pieces'),
        ('LTR', 'Liter'),
    )

    unit = models.CharField(
        max_length=200,
        choices=UNIT_CHOICES,
        default='KG'
    )

    container_amount = models.DecimalField(
        max_digits=5, decimal_places=2
    )
    price = models.DecimalField(
        max_digits=5, decimal_places=2
    )
    minimum_quantity = models.DecimalField(
        default=0, max_digits=5, decimal_places=2
    )
    current_stock = models.DecimalField(
        default=0, max_digits=5, decimal_places=2
    )
    order_quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.description

    def _get_unit_price(self):
        if self.price and self.container_amount:
            return round((self.price / self.container_amount), 2)
    unit_price = property(_get_unit_price)

    def _get_stock_value(self):
        if self.current_stock and self.price and self.container_amount:
            return round((self.current_stock * (self.price / self.container_amount)), 2)
    stock_value = property(_get_stock_value)

    class Meta:
        verbose_name = "Inventory Item"
        verbose_name_plural = "Inventory"


class MenuItemType(models.Model):
    menu_item_type = models.CharField(max_length=200)

    def __str__(self):
        return self.menu_item_type


class CourseType(models.Model):
    course_type = models.CharField(max_length=200)

    def __str__(self):
        return self.course_type


class MenuItem(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=2000, blank=True)
    menu_item_type = models.ForeignKey('MenuItemType',
                                       on_delete=models.PROTECT)
    course_type = models.ForeignKey('CourseType',
                                    on_delete=models.PROTECT)
    recipe = models.TextField(blank=True)

    def __str__(self):
        return self.name + ' (' + str(self.course_type) + '), Suggested selling price: €' + str(self.suggested_selling_price) + ')'

    def _get_uplift(self):
        if self.course_type.course_type == 'Drink':
            value = 1.90
        else:
            value = 1.65
        return value
    uplift = property(_get_uplift)

    def _get_suggested_selling_price(self):
        r = 0
        allingredients = Ingredient.objects.filter(
            menu_item__in=MenuItem.objects.filter(name=self.name))
        for item in allingredients:
            if item.unit == 'KG' or item.unit == 'L' or item.unit == 'PCS':
                r += ((item.ingredient.price / item.ingredient.container_amount) * item.amount)
            if item.unit == 'G' or item.unit == 'ML':
                r += ((item.ingredient.price / item.ingredient.container_amount) * item.amount/1000)
            else:
                r += ((item.ingredient.price / item.ingredient.container_amount) * item.amount/1000000)
        return round(Decimal((float(r)*self.uplift)), 2)
    suggested_selling_price = property(_get_suggested_selling_price)


class Ingredient(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Inventory, on_delete=models.PROTECT)

    UNIT_CHOICES = (
        ('MG', 'Milligram'),
        ('G', 'Gram'),
        ('KG', 'Kilogram'),
        ('ML', 'Milliliter'),
        ('L', 'Liter'),
        ('PCS', 'Pieces'),
    )

    unit = models.CharField(
        max_length=200,
        choices=UNIT_CHOICES,
        default='G'
    )

    amount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.menu_item.name


class Supplier(models.Model):
    name = models.CharField("Supplier Name", max_length=200)
    address_line1 = models.CharField("Address Line", max_length=200)
    address_line2 = models.CharField("Address Line", max_length=200)
    phone = models.CharField("Phone Number", max_length=10)
    email_address = models.CharField("Email Address", max_length=100, blank=True)

    def __str__(self):
        return self.name


class Menu(models.Model):
    name = models.CharField(max_length=128)
    menu_items = models.ManyToManyField(MenuItem)

    def _get_suggested_selling_price(self):
        r = 0
        for item in self.menu_items.all():
            r += item.suggested_selling_price
        return round(Decimal(r), 2)
    suggested_selling_price = property(_get_suggested_selling_price)

    def __str__(self):
        return self.name + ' (Suggested selling price: €' + str(self.suggested_selling_price) + ')'


class MenuCard(models.Model):
    name = models.CharField("Name of menu card", max_length=100)

    def __str__(self):
        return self.name


class MenuItemAddition(models.Model):
    menu_card = models.ForeignKey(MenuCard, on_delete=models.CASCADE)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.PROTECT)
    selling_price = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return str(self.menu_item.name) + ' (' + str(self.menu_item.course_type) + ") on " + str(self.menu_card) + " for €" + str(self.selling_price)

    class Meta:
        verbose_name = 'Menu Item'
        verbose_name_plural = 'Menu items'


class MenuAddition(models.Model):
    menu_card = models.ForeignKey(MenuCard, on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, on_delete=models.PROTECT)
    selling_price = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return str(self.menu.name) + " on " + str(self.menu_card) + " for €" + str(self.selling_price)

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'


class Order(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.DO_NOTHING)
    table_no = models.DecimalField(max_digits=2, decimal_places=0, default=0)
    completed = models.BooleanField(default=False)
    order_time = models.DateTimeField(default=datetime.datetime.now())
    completed_time = models.DateTimeField(null=True)
    remarks = models.CharField('Remarks', max_length=254)

    # Order items shouldn't be deleted in the admin page,
    # we can delete the complete items automatically when payment is processed.

    def __str__(self):
        return str(self.menu_item.name)


@receiver(post_save, sender=Order)
def update_inventory(sender, instance, created, **kwargs):
    if created:
        allingredients = Ingredient.objects.filter(
            menu_item__in=MenuItem.objects.filter(name=instance.menu_item.name))
        for ingred in allingredients:
            if ingred.unit == 'KG' or ingred.unit == 'L' or ingred.unit == 'PCS':
                inv = Inventory.objects.get(description=ingred.ingredient.description)
                inv.current_stock -= ingred.amount
                inv.save()
            if ingred.unit == 'G' or ingred.unit == 'ML':
                inv = Inventory.objects.get(description=ingred.ingredient.description)
                inv.current_stock -= ingred.amount/1000
                inv.save()
            else:
                inv = Inventory.objects.get(description=ingred.ingredient.description)
                inv.current_stock -= ingred.amount/1000000
                inv.save()


@receiver(pre_delete, sender=Order)
def restore_inventory(sender, instance, **kwargs):
    if instance.completed == False:
        allingredients = Ingredient.objects.filter(
            menu_item__in=MenuItem.objects.filter(name=instance.menu_item.name))
        for ingred in allingredients:
            if ingred.unit == 'KG' or ingred.unit == 'L' or ingred.unit == 'PCS':
                inv = Inventory.objects.get(description=ingred.ingredient.description)
                inv.current_stock += ingred.amount
                inv.save()
            if ingred.unit == 'G' or ingred.unit == 'ML':
                inv = Inventory.objects.get(description=ingred.ingredient.description)
                inv.current_stock += ingred.amount/1000
                inv.save()
            else:
                inv = Inventory.objects.get(description=ingred.ingredient.description)
                inv.current_stock += ingred.amount/1000000
                inv.save()

molveno/restaurant/forms.py
from django import forms
from .models import MenuItem, MenuItemAddition
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.forms.widgets import TextInput


class MenuItemForm(forms.Form):
    order_amount = forms.CharField(widget=TextInput(attrs={
        'min': '1', 'max': '10', 'type': 'number', 'placeholder': '1'}))


class MenuForm(forms.Form):
    order_amount = forms.CharField(widget=TextInput(attrs={
        'min': '1', 'max': '10', 'type': 'number', 'placeholder': '1'}))


class OrderForm(forms.Form):
    def __init__(self, orders, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for item in orders:
            amount = orders[item]['amount']
            price = orders[item]['price']
            self.fields[item] = forms.CharField(
                help_text=str(price),
                label_suffix='',
                widget=TextInput(attrs={
                    'min': '1', 'max': '10', 'type': 'number', 'value': amount
                }))

molveno/orders/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.base import TemplateView
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.apps import apps
from django.contrib.admin.sites import AlreadyRegistered
from django.contrib import admin, auth, messages
from restaurant.models import *
from django.forms import ModelForm
from datetime import datetime, timedelta


class IndexView(TemplateView):
    template_name = "orders/index.html"


class OrderHistoryView(generic.ListView):
    template_name = 'orders/order_history.html'
    context_object_name = 'complete_order_list'

    def get_queryset(self):
        return Order.objects.all().filter(completed=True)


class FoodOrdersList(TemplateView):
    template_name = 'orders/foodorders.html'

    def get_current_orders(self):
        current_orders = Order.objects.filter(completed=False)
        return current_orders

    def get_food_orders(self):
        current_orders = self.get_current_orders()
        food_orders = [i for i in current_orders if str(i.menu_item.course_type) != 'Drink']
        food_orders = sorted(food_orders, key=lambda order: order.order_time, reverse=False)
        for i in food_orders:
            displayed_time = i.order_time + timedelta(hours=2)
            i.order_time = format(displayed_time, '%H:%M')
        return food_orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['food_orders'] = self.get_food_orders()
        return context

class DrinkOrdersList(TemplateView):
    template_name = 'orders/drinkorders.html'

    def get_current_orders(self):
        current_orders = Order.objects.filter(completed=False)
        return current_orders

    def get_drink_orders(self):
        current_orders = self.get_current_orders()
        drink_orders = [i for i in current_orders if str(i.menu_item.course_type) == 'Drink']
        drink_orders = sorted(drink_orders, key=lambda order: order.order_time, reverse=False)
        for i in drink_orders:
            displayed_time = i.order_time + timedelta(hours=2)
            i.order_time = format(displayed_time, '%H:%M')
        return drink_orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['drink_orders'] = self.get_drink_orders()
        return context

class OrderRecipe(TemplateView):
    template_name = 'orders/orderrecipe.html'

    def get_ingredients(self):
        recipe_ingredients = Ingredient.objects.filter(menu_item__in=MenuItem.objects.filter(id = self.kwargs['pk']))
        return recipe_ingredients

    def get_recipe(self):
        recipe = Order.objects.filter(menu_item__in=MenuItem.objects.filter(id = self.kwargs['pk']))
        return recipe[0].menu_item.recipe

    def get_menu_item(self):
        orders = Order.objects.filter(menu_item__in=MenuItem.objects.filter(id = self.kwargs['pk']))
        return orders[0].menu_item.name

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipe'] = self.get_recipe()
        context['menuitem'] = self.get_menu_item()
        context['ingredients'] = self.get_ingredients()
        return context

molveno/restaurant/templates/restaurant/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Molveno Lakeside Restaurant</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'restaurant/style/base.css' %}">
</head>

<body>
  <div id="header">

    <div class="col-md-10 no-padding" id="header-left">
      <div class='molvenobrush'>Molveno Lake Resort</div>
      {% block header-text-left %}
      {% endblock %}
    </div>
    <div class="col-md-2 no-padding" id="header-right">
      <img class='logo-img' img src="/static/restaurant/images/Logo.jpg" alt="logo" />
      {% block header-text-right %}
      {% endblock %}
    </div>

  </div>


  <div class="main-content">

    <div class="row">
      <div class="col-md-10 no-padding">
        <p id="menu-card">
          {% block content %}
          {% endblock %}
        </p>
        {% block content-left %}
        {% endblock %}
      </div>

      <div class="col-md-2 no-padding">
        {% block content-right%}
        {% endblock %}
      </div>
      </div>

      </div>

molveno/restaurant/templates/restaurant/entry.html
{% extends 'restaurant/base.html' %}

{% block content %}
<div class="text-right">
  <div class="molvenobrush text-medium"> Table number: {{table_id}}</div>
  <a href="{% url 'restaurant:menucard' table_id %}" style="padding-left:1.5em">Menu Card</a>
</div>
  <h1 class="molvenobrush">What would you like to drink?</h1>
<ul>
  {%for drink in drinks_list%}
    <li class="no-bullets">
        <h3 class="molvenobrush">
          <a href="{% url 'restaurant:menu_item' drink.menu_item.id %}">{{drink.menu_item.name}}</a>
          <span> € {{drink.selling_price}}</span>
        </h3>
    </li>
  {% endfor %}
</ul>
</div>
{% endblock %}

molveno/restaurant/templates/restaurant/index.html
{% extends 'restaurant/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block header-text-right %}
Welcome, admin!
{% endblock %}

{% block page-title %}
  {{title}}
{% endblock %}
{% block content-left %}
<table class="table">
  <caption> {{table_title}} </caption>
  <tbody>
    {% for m in models %}
    <tr class="d-flex">

      <th scope="row">{{ m }}</th>
      <td>
        <a href="{{ m }}/add">Add</a>
      </td>
      <td>
        <a href="{{ m }}">Change</a>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}
{% block content-right %}
[more]<br />
{% endblock %}

molveno/restaurant/templates/restaurant/inventory.html
<!DOCTYPE html>
<html>
<head>
  <title>Molveno Restaurant - Inventory</title>
</head>
  <body>

    <h2>Inventory</h2>

    <p><h3>Current inventory:</h3></p>
    <p>butter, milk & eggs</p>
    <p><h3><a href="">Edit inventory</a></h3></p>

  </body>
</html>

molveno/restaurant/templates/restaurant/menu-add.html
{% extends 'restaurant/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block header-text-right %}
Welcome, admin!
{% endblock %}

{% block page-title %}
  Add a menu
{% endblock %}
{% block content-left %}
Name <input type="text" /> <br />
{% endblock %}
{% block content-right %}
[more]<br />
{% endblock %}

molveno/restaurant/templates/restaurant/menu-change.html
{% extends 'restaurant/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block header-text-right %}
Welcome, admin!
{% endblock %}

{% block page-title %}
  {{title}}
{% endblock %}
{% block content-left %}
<table class="table">
  <caption> {{table_title}} </caption>
  <tbody>
    {% for m in table %}
    <tr class="d-flex">

      <th scope="row">{{ m.name }}</th>
      <td>
        edit
      </td>
      <td>
        delete
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}
{% block content-right %}
[more]<br />
{% endblock %}

molveno/restaurant/templates/restaurant/menu.html
{% extends 'restaurant/base.html' %}
{% block content %}
<h1>{{ menu.menu.name }}</h1><br>
<b>price: €{{ menu.selling_price }}</b></br>
<form action="{% url 'restaurant:add-order-menu' menu.id %}" method="POST">
  {% csrf_token %}
  <div class='orderform'>
  <p><table>{{ form.as_table }}</table></p>
  <input type="submit" value="add to order" style="float: right;" />
</div>
</form>
<i>contains:</i>
<p>
{% for menu_item in menu.menu.menu_items.all %}
<p>
  <b>{{ menu_item.name }}</b><br>
  <i>ingredients:</i><br>
  <ul>
    {% for ingredient in menu_item.ingredient_set.all %}
      <li>{{ingredient.ingredient.description}}<br />
    {% endfor %}
  </ul>
</p>
{% endfor %}
</p>
{% endblock %}

molveno/restaurant/templates/restaurant/menu_item.html
{% extends 'restaurant/base.html' %}

{% block content %}

<p><h1>{{menu_item.name}}</h1></p>

<p><b>price: €{{selling_price}}</b><br>
{{menu_item.course_type}}, {{menu_item.menu_item_type}}<br>
<i>{{menu_item.description}}</i></p>

<p>
<b>ingredients:</b>
<ul>
  {% for ingredient in menu_item.ingredient_set.all %}
  <li>{{ingredient.ingredient.description}}</li>
  {% endfor %}
</ul>
</p>
<form action="{% url 'restaurant:addorder' menu_item.id %}" method="POST">
  {% csrf_token %}
  <div class='orderform'>
  <p><table>{{ form.as_table }}</table></p>
  <input type="submit" value="add to order" style="float: right;" />
</div>
</form>
<br><p><i>you are at table: {{table_id}}</i></p>
<a href="{% url 'restaurant:menucard' table_id %}"><i>back to menu</i></a>

{% endblock %}

molveno/restaurant/templates/restaurant/menucard_list.html
{% extends 'restaurant/base.html' %}
<!-- <div style="margin:auto; width:80%"> -->
{% block content %}
    <div class="text-right">
      <div class="molvenobrush text-medium"> Table number: {{table_id}}</div>
      <a href="{% url 'restaurant:orders' %}">My orders</a>
    </div>
      <h1 class="molvenobrush">MenuCard</h1>
      <div id="menu-items">
        {% for course in menucard_list %}
          {% if course %}
            <div class="no-bullets"><h2 class="molvenobrush">{{ course.0.menu_item.course_type }}</h2></div>
              <ul>
                {% for dish in course %}
                  <li class="no-bullets">
                    <h3 class="molvenobrush">
                      <a href="{% url 'restaurant:menu_item' dish.menu_item.id %}">{{ dish.menu_item.name }}</a>
                      <span> €{{dish.selling_price}}</span>
                    </h3>
                    <p class="menu-description">{{dish.menu_item.description}}</p>
                  </li>
                {% endfor %}
              </ul>
          {% endif %}
        {%empty%}
          <li>No menu items.</li>
      {%endfor%}
    </div>

    <div id="menus">
      <li class="no-bullets"> <h2 class="molvenobrush">Menus</h2></li>
      <ul>
        {% for type in menu_types %}
        <li class="no-bullets">
          <h3 class="molvenobrush">
            <span> <a href="{% url 'restaurant:menu' type.id %}">{{type.menu.name}}</a></span>
            <span> € {{type.selling_price}}</span>
          </h3>
          <ul>
            {% for d in menu_courses %}
            <li>{{d.name}}</li>
            {% endfor %}</ul>
        </li>

        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

molveno/restaurant/templates/restaurant/orders.html
{% extends 'restaurant/base.html' %}

{% block content %}

<h1>My orders for table {{table_id}}:</h1>
<div class='orderform'>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if orders %}
  <form action="{% url 'restaurant:orders' %}" method="POST">
  {% csrf_token %}
    <p>
      <table>
        {% for field in form %}
          <tr>
            <div class="fieldWrapper">
                {{ field.errors }}
                <td style="float: right;">{{ field }}x</td><td>{{ field.label }}</td>
                {% if field.help_text %}
                <td>€{{ field.help_text|safe }}</td>
                {% endif %}
            </div>
          </tr>
        {% endfor %}
        <tr>
          <td><br></td>
        </tr>
        <tr>
          <td></td><td><b style="float: right;">total:</b></td><td><b>€{{total}}</b></td>
        </tr>
        <tr>
          <td><br></td>
        </tr>
        <tr>
          <td><input type="submit" value="place order" style="float: right;"/></td>
          <td><i>or </i><a href="{% url 'restaurant:menucard' table_id %}">order more</a></td>
        </tr>
      </table>
    </p>
  </form>
  {% endif %}
  <p><br />
  <p><b>Placed orders for your table:</b></p>
  {% if placed_orders %}
    <table style="float: right;">
        {% for item, attributes in placed_orders.items %}
          <tr>
            <td>{{attributes.amount}}x {{item}}</td><td style="text-align: right;">€{{attributes.selling_price}}</td>
          </tr>
        {% endfor %}
      <tr>
        <td><br></td>
      </tr>
      <tr>
        <td style="float: right;"><b>total:</b></td><td style="text-align: right;"><b>€{{total_pice}}</b></td>
      </tr>
    </table>
  {% else %}
  <ul>
    <li>No orders placed yet!
  </ul>
  {% endif %}
  </p>
</div>
<p><a href="{% url 'restaurant:menucard' table_id %}"><i>back to menu</i></a></p>
{% endblock %}

molveno/restaurant/templates/restaurant/rubens_old_admin.html
{% extends 'restaurant/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block header-text-right %}
Welcome, admin!
{% endblock %}

{% block page-title %}
  {{title}}
{% endblock %}
{% block content-left %}
<table class="table">
  <caption> {{table_title}} </caption>
  <tbody>
    {% for m in models %}
    <tr class="d-flex">

      <th scope="row">{{ m }}</th>
      <td>
        <a href="{{ m }}/add">Add</a>
      </td>
      <td>
        <a href="{{ m }}">Change</a>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}
{% block content-right %}
[more]<br />
{% endblock %}

molveno/restaurant/templates/restaurant/supplier-add.html
{% extends 'restaurant/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block header-text-right %}
Welcome, admin!
{% endblock %}

{% block page-title %}
  {{title}}
{% endblock %}
{% block content-left %}
<table class="table">
  <caption> {{table_title}} </caption>
  <tbody>
    {% for m in models %}
    <tr class="d-flex">

      <th scope="row">{{ m }}</th>
      <td>
        <a href="{{ m }}/add">Add</a>
      </td>
      <td>
        <a href="{{ m }}">Change</a>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}
{% block content-right %}
[more]<br />
{% endblock %}

molveno/restaurant/templates/restaurant/supplier-change.html
{% extends 'restaurant/base.html' %}
{% block header-text-left %}
Molveno
{% endblock %}

{% block header-text-right %}
Welcome, admin!
{% endblock %}

{% block page-title %}
  {{title}}
{% endblock %}
{% block content-left %}
<table class="table">
  <caption> {{table_title}} </caption>
  <tbody>
    {% for m in models %}
    <tr class="d-flex">

      <th scope="row">{{ m }}</th>
      <td>
        <a href="{{ m }}/add">Add</a>
      </td>
      <td>
        <a href="{{ m }}">Change</a>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}
{% block content-right %}
[more]<br />
{% endblock %}

molveno/restaurant/templates/restaurant/waiter.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Molveno Lakeside Restaurant</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'restaurant/style/base.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div id="header">

    <div class="col-md-10 no-padding" id="header-left">
      <div class='molvenobrush'>Molveno Lake Resort</div>
      {% block header-text-left %}
      {% endblock %}
    </div>
    <div class="col-md-2 no-padding" id="header-right">
      <img class='logo-img' img src="/static/restaurant/images/Logo.jpg" alt="logo" />
      {% block header-text-right %}
      {% endblock %}
    </div>

  </div>

{% block content %}
  <h3 class="molvenobrush main-content">Your waiter will be with you shortly!</h3>
  <br><br>
  <a href="{% url 'restaurant:menucard' table_id %}" style="padding-left:1.5em"><i>back to menu</i></a>
{% endblock %}
</body>
</html>